// AUTO-GENERATED by scripts/generate-isochrone.mjs — do not edit by hand.
// Fixed forwarder: the polygon data lives in polygonData.ts (auto-generated,
// one entry per journal). This file never gains new imports when journals are
// added — it simply re-exports the entire data module.

export { POLYGON_POINTS, getPolygonPoints } from "./polygonData";
