// Outer Sarjapur Road (Top Choice) Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const outerSarjapurRoadIsochronePoints: Array<[number, number]> = [
  [12.946953, 77.699195],
  [12.947068, 77.698195],
  [12.943896, 77.695322],
  [12.940182, 77.693195],
  [12.941025, 77.685195],
  [12.936896, 77.684905],
  [12.934195, 77.688494],
  [12.932427, 77.687726],
  [12.937896, 77.698492],
  [12.940896, 77.69672],
  [12.946851, 77.698239],
  [12.946894, 77.699193],
  [12.946953, 77.699195],
];
