// JP Nagar 7th Phase Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const jpNagar7thPhaseIsochronePoints: Array<[number, number]> = [
  [12.901965, 77.581452],
  [12.894264, 77.579745],
  [12.891487, 77.571381],
  [12.888967, 77.579861],
  [12.884558, 77.580912],
  [12.883169, 77.583452],
  [12.887757, 77.583452],
  [12.888558, 77.589],
  [12.890558, 77.586987],
  [12.892382, 77.590627],
  [12.896273, 77.585452],
  [12.893551, 77.583445],
  [12.898558, 77.583896],
  [12.901965, 77.581452],
];
