// Whitefield Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=8, generalize=150, denoise=0.1)
export const whitefieldIsochronePoints: Array<[number, number]> = [
  [12.985875, 77.734086],
  [12.983621, 77.731944],
  [12.973337, 77.732228],
  [12.972213, 77.727819],
  [12.97476, 77.727086],
  [12.97148, 77.723756],
  [12.968533, 77.729139],
  [12.965422, 77.728028],
  [12.962505, 77.732111],
  [12.960071, 77.732086],
  [12.967739, 77.735826],
  [12.965888, 77.743086],
  [12.96848, 77.746302],
  [12.973387, 77.734993],
  [12.976741, 77.735824],
  [12.97648, 77.741082],
  [12.980718, 77.735086],
  [12.985875, 77.734086],
];
