// Outer Ring Road (Bellandur / Ecospace) Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const outerRingRoadBellandurEcospaceIsochronePoints: Array<[number, number]> = [
  [12.929524, 77.6824],
  [12.928818, 77.6764],
  [12.925279, 77.674821],
  [12.9217, 77.666895],
  [12.921593, 77.668293],
  [12.9227, 77.672371],
  [12.923832, 77.6744],
  [12.922449, 77.6754],
  [12.925092, 77.677792],
  [12.922321, 77.6814],
  [12.9277, 77.683948],
  [12.929524, 77.6824],
];
