// Bellandur - Panathur (Flat) Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const bellandurPanathurIsochronePoints: Array<[number, number]> = [
  [12.945129, 77.698285],
  [12.939868, 77.693579],
  [12.934868, 77.696712],
  [12.931296, 77.695285],
  [12.935921, 77.699285],
  [12.93434, 77.704285],
  [12.935868, 77.7057],
  [12.938819, 77.702236],
  [12.940868, 77.704725],
  [12.943082, 77.703499],
  [12.945129, 77.698285],
];
