// Hebbal Corridor Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const hebbalCorridorIsochronePoints: Array<[number, number]> = [
  [13.041401, 77.594785],
  [13.041362, 77.589485],
  [13.039362, 77.591498],
  [13.034758, 77.588785],
  [13.035798, 77.591221],
  [13.031526, 77.598785],
  [13.032269, 77.602785],
  [13.028666, 77.604785],
  [13.029362, 77.606113],
  [13.035362, 77.606919],
  [13.039526, 77.604949],
  [13.037003, 77.602785],
  [13.038362, 77.601002],
  [13.039927, 77.60235],
  [13.041401, 77.594785],
];
