// Manyata Tech Park Corridor Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const manyataTechParkCorridorIsochronePoints: Array<[number, number]> = [
  [13.050941, 77.6226],
  [13.0502, 77.618816],
  [13.0422, 77.620938],
  [13.0412, 77.617366],
  [13.037603, 77.622003],
  [13.033865, 77.6226],
  [13.037531, 77.6256],
  [13.032522, 77.6296],
  [13.0352, 77.629616],
  [13.0382, 77.627845],
  [13.0402, 77.62973],
  [13.0412, 77.625365],
  [13.0462, 77.627903],
  [13.045754, 77.6266],
  [13.042997, 77.623397],
  [13.050941, 77.6226],
];
