// Embassy TechVillage / Panathur Arc Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const embassyTechVillagePanathurArcIsochronePoints: Array<[number, number]> = [
  [12.936583, 77.6971],
  [12.931723, 77.6951],
  [12.934403, 77.690096],
  [12.93054, 77.6921],
  [12.9304, 77.69446],
  [12.9304, 77.690953],
  [12.9274, 77.688705],
  [12.92362, 77.69432],
  [12.9194, 77.695161],
  [12.917166, 77.698333],
  [12.9244, 77.697404],
  [12.9274, 77.70253],
  [12.9274, 77.699688],
  [12.9304, 77.700407],
  [12.936583, 77.6971],
];
