// Thanisandra Main Rd Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const thanisandraMainRdIsochronePoints: Array<[number, number]> = [
  [13.085078, 77.634453],
  [13.078314, 77.631835],
  [13.079697, 77.626998],
  [13.076186, 77.631453],
  [13.071697, 77.629831],
  [13.068155, 77.633453],
  [13.074697, 77.638406],
  [13.076697, 77.635106],
  [13.085078, 77.634453],
];
