// Jayanagar 4th Block Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const jayanagar4thBlockIsochronePoints: Array<[number, number]> = [
  [12.937281, 77.585484],
  [12.936651, 77.580037],
  [12.932204, 77.580121],
  [12.927204, 77.574207],
  [12.926204, 77.576812],
  [12.921916, 77.574484],
  [12.922206, 77.576486],
  [12.915683, 77.583484],
  [12.921204, 77.591248],
  [12.924204, 77.589651],
  [12.928204, 77.59327],
  [12.930182, 77.589462],
  [12.933204, 77.58949],
  [12.93393, 77.58521],
  [12.937281, 77.585484],
];
