// Sarjapur Road Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const sarjapurRoadIsochronePoints: Array<[number, number]> = [
  [12.914094, 77.68647],
  [12.91254, 77.68247],
  [12.913796, 77.67699],
  [12.910218, 77.681892],
  [12.90443, 77.68447],
  [12.908007, 77.685258],
  [12.906195, 77.69847],
  [12.909499, 77.69647],
  [12.910411, 77.688085],
  [12.914094, 77.68647],
];
