// Devanahalli Airport Corridor (Plot) Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const devanahalliAirportCorridorIsochronePoints: Array<[number, number]> = [
  [13.215007, 77.698624],
  [13.213104, 77.697624],
  [13.215152, 77.689624],
  [13.212489, 77.688229],
  [13.210745, 77.69088],
  [13.211489, 77.705576],
  [13.215007, 77.698624],
];
