// Hebbal Airport Belt Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const hebbalAirportBeltIsochronePoints: Array<[number, number]> = [
  [13.204324, 77.743834],
  [13.204177, 77.740555],
  [13.198502, 77.739437],
  [13.202829, 77.744903],
  [13.204324, 77.743834],
];
