// Banashankari 3rd Stage Drive-Time Isochrone (untrimmed reachable zone)
// Auto-generated by scripts/generate-isochrone.mjs from Valhalla routing
//   regenerated via --batch (time=5, generalize=150, denoise=0.1)
export const banashankari3rdStageIsochronePoints: Array<[number, number]> = [
  [12.929112, 77.549807],
  [12.92892, 77.545396],
  [12.925789, 77.549807],
  [12.929112, 77.549807],
];
